name: debugger-action
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
